version: '3'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack-static-content
    ports:
      - '4566-4599:4566-4599'
      - '8080:8080'
    environment:
      - SERVICES=es,s3
      - DEFAULT_REGION=eu-west-1
  database:
    image: postgres
    container_name: pg-db
    environment:
      - POSTGRES_DB=Harare_db
      - POSTGRES_PASSWORD= postgrest
    ports:
      - '5432:5432'
  mockServer:
    image: mockserver/mockserver:mockserver-5.10.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: '/config/initializerJson.json'
      MOCKSERVER_WATCH_INITIALIZATION_JSON: 'true'
    volumes:
        - '${PWD}/mock:/config'
